"""OCR weak labeling package."""

from .preprocess import PreprocessConfig, preprocess_patch_image
from .preprocess_bdrc import BDRCPreprocessConfig, preprocess_image_bdrc, pad_ocr_line, bdrc_image_to_normalized_tensor
from .preprocess_rgb import RGBLinePreprocessConfig, preprocess_image_rgb_lines
from .line_segmentation import (
    DEFAULT_LINE_SEGMENTATION_CONF,
    DEFAULT_LINE_SEGMENTATION_IMGSZ,
    DEFAULT_LINE_SEGMENTATION_PREPROCESS,
    LinePrediction,
    apply_line_segmentation_preprocess,
    coerce_polygon_points,
    normalize_line_segmentation_preprocess_pipeline,
    polygon_to_box,
    polygon_to_yolo_segment_line,
    predict_line_regions,
    sort_line_predictions,
)
from .bdrc_inference import (
    BDRCLineModelConfig,
    BDRCLinePrediction,
    BDRCOCRModelConfig,
    DEFAULT_BDRC_LINE_BBOX_TOLERANCE,
    DEFAULT_BDRC_LINE_K_FACTOR,
    find_bdrc_line_model_dirs,
    find_bdrc_ocr_model_dirs,
    is_bdrc_line_model_dir,
    is_bdrc_ocr_model_dir,
    predict_bdrc_line_regions,
    resolve_bdrc_line_model_config,
    resolve_bdrc_ocr_model_config,
    run_bdrc_ocr,
)
from .bdrc_model_download import (
    BDRC_APP_RELEASE_TAG,
    BDRC_OCR_BUNDLE_TAG,
    DEFAULT_BDRC_MODELS_ROOT,
    DEFAULT_BDRC_LINE_URL,
    DEFAULT_BDRC_LAYOUT_URL,
    DEFAULT_BDRC_OCR_ZIP_URL,
    choose_default_bdrc_ocr_model_dir,
    ensure_default_bdrc_line_assets,
    ensure_default_bdrc_ocr_models,
)
from .weak_labeler import WeakOCRConfig, run_weak_ocr_labeler

__all__ = [
    "WeakOCRConfig",
    "run_weak_ocr_labeler",
    "PreprocessConfig",
    "preprocess_patch_image",
    "BDRCPreprocessConfig",
    "preprocess_image_bdrc",
    "RGBLinePreprocessConfig",
    "preprocess_image_rgb_lines",
    "pad_ocr_line",
    "bdrc_image_to_normalized_tensor",
    "DEFAULT_LINE_SEGMENTATION_CONF",
    "DEFAULT_LINE_SEGMENTATION_IMGSZ",
    "DEFAULT_LINE_SEGMENTATION_PREPROCESS",
    "LinePrediction",
    "apply_line_segmentation_preprocess",
    "coerce_polygon_points",
    "normalize_line_segmentation_preprocess_pipeline",
    "polygon_to_box",
    "polygon_to_yolo_segment_line",
    "predict_line_regions",
    "sort_line_predictions",
    "BDRCLineModelConfig",
    "BDRCLinePrediction",
    "BDRCOCRModelConfig",
    "DEFAULT_BDRC_LINE_BBOX_TOLERANCE",
    "DEFAULT_BDRC_LINE_K_FACTOR",
    "find_bdrc_line_model_dirs",
    "find_bdrc_ocr_model_dirs",
    "is_bdrc_line_model_dir",
    "is_bdrc_ocr_model_dir",
    "predict_bdrc_line_regions",
    "resolve_bdrc_line_model_config",
    "resolve_bdrc_ocr_model_config",
    "run_bdrc_ocr",
    "BDRC_APP_RELEASE_TAG",
    "BDRC_OCR_BUNDLE_TAG",
    "DEFAULT_BDRC_MODELS_ROOT",
    "DEFAULT_BDRC_LINE_URL",
    "DEFAULT_BDRC_LAYOUT_URL",
    "DEFAULT_BDRC_OCR_ZIP_URL",
    "choose_default_bdrc_ocr_model_dir",
    "ensure_default_bdrc_line_assets",
    "ensure_default_bdrc_ocr_models",
]
